### ISSUE TITLE
Test fails when computing component on updates

### ISSUE THREAD

**Issue by ooade** [ooade/preact-side-effect#1]
```js
1) react-side-effect SideEffect component with DOM should only recompute when component updates:
     ReferenceError: Text is not defined
      at idiff (node_modules/preact/src/vdom/diff.js:149:3)
      at diff (node_modules/preact/src/vdom/diff.js:45:15)
      at renderComponent (node_modules/preact/src/vdom/component.js:142:19)
      at setComponentProps (node_modules/preact/src/vdom/component.js:39:12)
      at renderComponent (node_modules/preact/src/vdom/component.js:115:35)
      at setComponentProps (node_modules/preact/src/vdom/component.js:39:12)
      at buildComponentFromVNode (node_modules/preact/src/vdom/component.js:209:3)
      at idiff (node_modules/preact/src/vdom/diff.js:96:16)
      at diff (node_modules/preact/src/vdom/diff.js:45:15)
      at Object.render (node_modules/preact/dist/preact.js:409:16)
      at render$1 (node_modules/preact-compat/src/index.js:145:12)
      at Context.<anonymous> (test/index.spec.js:228:9)
```

**Comment by ooade** [comment]
I switched to React for the tests
